export const ENROLLED_COURSE_CREATE_REQUEST = "ENROLLED_COURSE_CREATE_REQUEST";
export const ENROLLED_COURSE_CREATE_SUCCESS = "ENROLLED_COURSE_CREATE_SUCCESS";
export const ENROLLED_COURSE_CREATE_FAIL = "ENROLLED_COURSE_CREATE_FAIL";
export const ENROLLED_COURSE_CREATE_RESET = "ENROLLED_COURSE_CREATE_RESET";
